version: "3.8"

services:
  backend:
    build: ./megadisp-backend
    container_name: megadisp-backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000 
      DB_USER: dplapp
      DB_PASSWORD: dplapp
      DB_CONNECT: 172.16.0.51:1521/pamsprod
    restart: unless-stopped
    networks:
      - megadisp-nt

  frontend:
    build: ./megadisp-frontend
    container_name: megadisp-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - megadisp-nt

networks:
  megadisp-nt:
    driver: bridge
